module.exports = {
  SET_APP_CONFIG: 'SET_APP_CONFIG',
  SHOW_TOAST: 'SHOW_TOAST',
  HIDE_TOAST: 'HIDE_TOAST',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
  SET_WINDOW_SIZE: 'SET_WINDOW_SIZE'
};
